set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(MINGW32_ROOT /tmp/opencode/mingw32/root/usr)
set(CMAKE_C_COMPILER ${MINGW32_ROOT}/bin/i686-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER ${MINGW32_ROOT}/bin/i686-w64-mingw32-g++)
set(CMAKE_RC_COMPILER ${MINGW32_ROOT}/bin/i686-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH ${MINGW32_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
